# Generated by Django 4.1.4 on 2022-12-13 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('time_written', models.DateTimeField(default=datetime.datetime.now)),
                ('content', models.CharField(max_length=999999999999999999999999999999999999999999999)),
                ('image_exp', models.ImageField(upload_to='images')),
            ],
        ),
    ]
